# Generated by Django 5.2.17 on 2026-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_crmdashboardpage_customer_note_delete_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AI Phân loại'),
        ),
        migrations.AddField(
            model_name='note',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI Tóm tắt'),
        ),
    ]
