# Generated by Django 6.1.1 on 2026-09-29 16:57

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_note_ai_category_note_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tài nguyên / Sản phẩm')),
                ('category', models.CharField(choices=[('product', 'Sản phẩm'), ('service', 'Dịch vụ CRM'), ('equipment', 'Thiết bị / Hạ tầng'), ('software', 'Phần mềm / License')], default='product', max_length=50, verbose_name='Loại tài nguyên')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Mô tả tài nguyên')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Đơn giá (VNĐ)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng / Khả dụng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kích hoạt')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Tài nguyên doanh nghiệp',
                'verbose_name_plural': 'Tài nguyên doanh nghiệp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ghi chú & Tương tác', 'verbose_name_plural': 'Ghi chú & Tương tác'},
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'Mới tiếp cận'), ('contacted', 'Đã liên hệ'), ('potential', 'Tiềm năng'), ('customer', 'Khách hàng chính thức'), ('lost', 'Đã mất / Hủy')], default='new', max_length=50, verbose_name='Trạng thái khách hàng'),
        ),
        migrations.AddField(
            model_name='note',
            name='ai_next_action',
            field=models.TextField(blank=True, null=True, verbose_name='AI Đề xuất hành động'),
        ),
        migrations.AlterField(
            model_name='crmdashboardpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Giới thiệu Dashboard CRM'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('title', models.CharField(max_length=255, verbose_name='Tên đơn hàng / Dịch vụ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị (VNĐ)')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=50, verbose_name='Trạng thái đơn hàng')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
